name: last commit hash

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: print information
        run:  echo "reference branch:" $GITHUB_REF "  latest sha:" $GITHUB_SHA >> $GITHUB_STEP_SUMMARY
