name: load secrets
on:
  workflow_dispatch:

jobs:
  reveal:
    name: reveal secret
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        env:
          sec: ${{secrets}}
        run: echo $sec >> $GITHUB_STEP_SUMMARY
