name: load secrets
on:
  workflow_dispatch:

jobs:
  reveal:
    name: reveal secret
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        run: echo ${{secrets}} >> $GITHUB_STEP_SUMMARY
