name: load secrets

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN : ${{secrets.GTHB_TOKEN}}

jobs:
  reveal:
    name: reveal secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install req
        run: |
          pip3 install requests   

      - name: load secs to env1
        run: |
          python3 -c """
          import os
          secret = 'MY_SECRET'
          command_s = f'echo "${secret}=$' + "{{" + f"secrets.{secret}" + '}}"'
          os.system(command_s) 
          """

      # - name: load secs to env
      #   run: |
      #     python3 blocks/load_secret.py

      - name: echo secret
        run: |
          echo $GITHUB_ENV
